export interface CityState {
  city: string;
  state: string;
}

export const CITIES_AND_STATES: CityState[] = [
  // Delhi
  { city: "New Delhi", state: "Delhi" },
  { city: "Delhi", state: "Delhi" },
  { city: "Dwarka", state: "Delhi" },
  { city: "Rohini", state: "Delhi" },
  
  // Maharashtra
  { city: "Mumbai", state: "Maharashtra" },
  { city: "Pune", state: "Maharashtra" },
  { city: "Nagpur", state: "Maharashtra" },
  { city: "Thane", state: "Maharashtra" },
  { city: "Nashik", state: "Maharashtra" },
  { city: "Kalyan-Dombivli", state: "Maharashtra" },
  { city: "Vasai-Virar", state: "Maharashtra" },
  { city: "Aurangabad", state: "Maharashtra" },
  { city: "Navi Mumbai", state: "Maharashtra" },
  { city: "Solapur", state: "Maharashtra" },
  { city: "Mira-Bhayandar", state: "Maharashtra" },
  { city: "Bhiwandi", state: "Maharashtra" },
  { city: "Amravati", state: "Maharashtra" },
  { city: "Nanded", state: "Maharashtra" },
  { city: "Kolhapur", state: "Maharashtra" },
  { city: "Ulhasnagar", state: "Maharashtra" },
  { city: "Sangli", state: "Maharashtra" },
  { city: "Malegaon", state: "Maharashtra" },
  { city: "Akola", state: "Maharashtra" },
  { city: "Latur", state: "Maharashtra" },
  { city: "Dhule", state: "Maharashtra" },
  { city: "Ahmednagar", state: "Maharashtra" },
  { city: "Chandrapur", state: "Maharashtra" },
  { city: "Parbhani", state: "Maharashtra" },
  { city: "Ichalkaranji", state: "Maharashtra" },
  { city: "Jalna", state: "Maharashtra" },
  { city: "Ambernath", state: "Maharashtra" },
  { city: "Bhusaul", state: "Maharashtra" },
  { city: "Panvel", state: "Maharashtra" },

  // Karnataka
  { city: "Bengaluru", state: "Karnataka" },
  { city: "Hubli-Dharwad", state: "Karnataka" },
  { city: "Mysore", state: "Karnataka" },
  { city: "Kalaburagi", state: "Karnataka" },
  { city: "Mangalore", state: "Karnataka" },
  { city: "Belgaum", state: "Karnataka" },
  { city: "Davangere", state: "Karnataka" },
  { city: "Bellary", state: "Karnataka" },
  { city: "Vijayapura", state: "Karnataka" },
  { city: "Shivamogga", state: "Karnataka" },
  { city: "Tumkur", state: "Karnataka" },
  { city: "Raichur", state: "Karnataka" },
  { city: "Bidar", state: "Karnataka" },
  { city: "Hospet", state: "Karnataka" },

  // Madhya Pradesh
  { city: "Indore", state: "Madhya Pradesh" },
  { city: "Bhopal", state: "Madhya Pradesh" },
  { city: "Jabalpur", state: "Madhya Pradesh" },
  { city: "Gwalior", state: "Madhya Pradesh" },
  { city: "Ujjain", state: "Madhya Pradesh" },
  { city: "Sagar", state: "Madhya Pradesh" },
  { city: "Dewas", state: "Madhya Pradesh" },
  { city: "Satna", state: "Madhya Pradesh" },
  { city: "Ratlam", state: "Madhya Pradesh" },
  { city: "Rewa", state: "Madhya Pradesh" },
  { city: "Katni", state: "Madhya Pradesh" },
  { city: "Singrauli", state: "Madhya Pradesh" },
  { city: "Burhanpur", state: "Madhya Pradesh" },
  { city: "Khandwa", state: "Madhya Pradesh" },
  { city: "Morena", state: "Madhya Pradesh" },
  { city: "Bhind", state: "Madhya Pradesh" },
  { city: "Chhindwara", state: "Madhya Pradesh" },
  { city: "Guna", state: "Madhya Pradesh" },
  { city: "Shivpuri", state: "Madhya Pradesh" },

  // Gujarat
  { city: "Ahmedabad", state: "Gujarat" },
  { city: "Surat", state: "Gujarat" },
  { city: "Vadodara", state: "Gujarat" },
  { city: "Rajkot", state: "Gujarat" },
  { city: "Bhavnagar", state: "Gujarat" },
  { city: "Jamnagar", state: "Gujarat" },
  { city: "Junagadh", state: "Gujarat" },
  { city: "Gandhidham", state: "Gujarat" },
  { city: "Nadiad", state: "Gujarat" },
  { city: "Gandhinagar", state: "Gujarat" },
  { city: "Anand", state: "Gujarat" },
  { city: "Morbi", state: "Gujarat" },
  { city: "Mehsana", state: "Gujarat" },
  { city: "Surendranagar", state: "Gujarat" },
  { city: "Bharuch", state: "Gujarat" },
  { city: "Vapi", state: "Gujarat" },
  { city: "Navsari", state: "Gujarat" },

  // Tamil Nadu
  { city: "Chennai", state: "Tamil Nadu" },
  { city: "Coimbatore", state: "Tamil Nadu" },
  { city: "Madurai", state: "Tamil Nadu" },
  { city: "Tiruchirappalli", state: "Tamil Nadu" },
  { city: "Salem", state: "Tamil Nadu" },
  { city: "Tiruppur", state: "Tamil Nadu" },
  { city: "Erode", state: "Tamil Nadu" },
  { city: "Vellore", state: "Tamil Nadu" },
  { city: "Thoothukudi", state: "Tamil Nadu" },
  { city: "Dindigul", state: "Tamil Nadu" },
  { city: "Thanjavur", state: "Tamil Nadu" },
  { city: "Ranipet", state: "Tamil Nadu" },
  { city: "Sivakasi", state: "Tamil Nadu" },
  { city: "Karur", state: "Tamil Nadu" },
  { city: "Ooty", state: "Tamil Nadu" },
  { city: "Hosur", state: "Tamil Nadu" },
  { city: "Nagercoil", state: "Tamil Nadu" },
  { city: "Kancheepuram", state: "Tamil Nadu" },

  // Uttar Pradesh
  { city: "Lucknow", state: "Uttar Pradesh" },
  { city: "Kanpur", state: "Uttar Pradesh" },
  { city: "Ghaziabad", state: "Uttar Pradesh" },
  { city: "Agra", state: "Uttar Pradesh" },
  { city: "Meerut", state: "Uttar Pradesh" },
  { city: "Varanasi", state: "Uttar Pradesh" },
  { city: "Prayagraj", state: "Uttar Pradesh" },
  { city: "Bareilly", state: "Uttar Pradesh" },
  { city: "Aligarh", state: "Uttar Pradesh" },
  { city: "Moradabad", state: "Uttar Pradesh" },
  { city: "Saharanpur", state: "Uttar Pradesh" },
  { city: "Gorakhpur", state: "Uttar Pradesh" },
  { city: "Noida", state: "Uttar Pradesh" },
  { city: "Greater Noida", state: "Uttar Pradesh" },
  { city: "Firozabad", state: "Uttar Pradesh" },
  { city: "Jhansi", state: "Uttar Pradesh" },
  { city: "Muzaffarnagar", state: "Uttar Pradesh" },
  { city: "Mathura", state: "Uttar Pradesh" },
  { city: "Ayodhya", state: "Uttar Pradesh" },
  { city: "Rampur", state: "Uttar Pradesh" },
  { city: "Shahjahanpur", state: "Uttar Pradesh" },
  { city: "Farrukhabad", state: "Uttar Pradesh" },
  { city: "Hapur", state: "Uttar Pradesh" },
  { city: "Etawah", state: "Uttar Pradesh" },
  { city: "Mirzapur", state: "Uttar Pradesh" },
  { city: "Bulandshahr", state: "Uttar Pradesh" },
  { city: "Sambhal", state: "Uttar Pradesh" },
  { city: "Amroha", state: "Uttar Pradesh" },
  { city: "Hardoi", state: "Uttar Pradesh" },
  { city: "Fatehpur", state: "Uttar Pradesh" },
  { city: "Rae Bareli", state: "Uttar Pradesh" },
  { city: "Orai", state: "Uttar Pradesh" },
  { city: "Bahraich", state: "Uttar Pradesh" },
  { city: "Jaunpur", state: "Uttar Pradesh" },

  // West Bengal
  { city: "Kolkata", state: "West Bengal" },
  { city: "Howrah", state: "West Bengal" },
  { city: "Darjeeling", state: "West Bengal" },
  { city: "Siliguri", state: "West Bengal" },
  { city: "Asansol", state: "West Bengal" },
  { city: "Durgapur", state: "West Bengal" },
  { city: "Maheshtala", state: "West Bengal" },
  { city: "Rajpur Sonarpur", state: "West Bengal" },
  { city: "Gopalpur", state: "West Bengal" },
  { city: "Bhatpara", state: "West Bengal" },
  { city: "Panihati", state: "West Bengal" },
  { city: "Kamarhati", state: "West Bengal" },
  { city: "Bardhaman", state: "West Bengal" },
  { city: "Kulti", state: "West Bengal" },
  { city: "Bally", state: "West Bengal" },
  { city: "Barasat", state: "West Bengal" },
  { city: "Uluberia", state: "West Bengal" },
  { city: "Naihati", state: "West Bengal" },
  { city: "Kharagpur", state: "West Bengal" },
  { city: "Haldia", state: "West Bengal" },

  // Rajasthan
  { city: "Jaipur", state: "Rajasthan" },
  { city: "Jodhpur", state: "Rajasthan" },
  { city: "Kota", state: "Rajasthan" },
  { city: "Bikaner", state: "Rajasthan" },
  { city: "Ajmer", state: "Rajasthan" },
  { city: "Udaipur", state: "Rajasthan" },
  { city: "Bhilwara", state: "Rajasthan" },
  { city: "Alwar", state: "Rajasthan" },
  { city: "Bharatpur", state: "Rajasthan" },
  { city: "Sikar", state: "Rajasthan" },
  { city: "Pali", state: "Rajasthan" },
  { city: "Sri Ganganagar", state: "Rajasthan" },

  // Andhra Pradesh
  { city: "Visakhapatnam", state: "Andhra Pradesh" },
  { city: "Vijayawada", state: "Andhra Pradesh" },
  { city: "Guntur", state: "Andhra Pradesh" },
  { city: "Nellore", state: "Andhra Pradesh" },
  { city: "Kurnool", state: "Andhra Pradesh" },
  { city: "Rajahmundry", state: "Andhra Pradesh" },
  { city: "Tirupati", state: "Andhra Pradesh" },
  { city: "Kakinada", state: "Andhra Pradesh" },
  { city: "Anantapur", state: "Andhra Pradesh" },
  { city: "Kadapa", state: "Andhra Pradesh" },
  { city: "Eluru", state: "Andhra Pradesh" },
  { city: "Vizianagaram", state: "Andhra Pradesh" },
  { city: "Ongole", state: "Andhra Pradesh" },

  // Telangana
  { city: "Hyderabad", state: "Telangana" },
  { city: "Warangal", state: "Telangana" },
  { city: "Nizamabad", state: "Telangana" },
  { city: "Karimnagar", state: "Telangana" },
  { city: "Ramagundam", state: "Telangana" },
  { city: "Khammam", state: "Telangana" },
  { city: "Mahbubnagar", state: "Telangana" },

  // Bihar
  { city: "Patna", state: "Bihar" },
  { city: "Gaya", state: "Bihar" },
  { city: "Bhagalpur", state: "Bihar" },
  { city: "Muzaffarpur", state: "Bihar" },
  { city: "Darbhanga", state: "Bihar" },
  { city: "Bihar Sharif", state: "Bihar" },
  { city: "Arrah", state: "Bihar" },
  { city: "Begusarai", state: "Bihar" },
  { city: "Purnia", state: "Bihar" },
  { city: "Katihar", state: "Bihar" },
  { city: "Munger", state: "Bihar" },
  { city: "Chhapra", state: "Bihar" },

  // Punjab
  { city: "Ludhiana", state: "Punjab" },
  { city: "Amritsar", state: "Punjab" },
  { city: "Jalandhar", state: "Punjab" },
  { city: "Patiala", state: "Punjab" },
  { city: "Bathinda", state: "Punjab" },
  { city: "Hoshiarpur", state: "Punjab" },
  { city: "Mohali", state: "Punjab" },
  { city: "Pathankot", state: "Punjab" },

  // Haryana
  { city: "Faridabad", state: "Haryana" },
  { city: "Gurugram", state: "Haryana" },
  { city: "Panipat", state: "Haryana" },
  { city: "Ambala", state: "Haryana" },
  { city: "Yamunanagar", state: "Haryana" },
  { city: "Rohtak", state: "Haryana" },
  { city: "Hisar", state: "Haryana" },
  { city: "Karnal", state: "Haryana" },
  { city: "Sonipat", state: "Haryana" },
  { city: "Panchkula", state: "Haryana" },

  // Odisha
  { city: "Bhubaneswar", state: "Odisha" },
  { city: "Cuttack", state: "Odisha" },
  { city: "Rourkela", state: "Odisha" },
  { city: "Berhampur", state: "Odisha" },
  { city: "Sambalpur", state: "Odisha" },
  { city: "Puri", state: "Odisha" },

  // Kerala
  { city: "Thiruvananthapuram", state: "Kerala" },
  { city: "Kochi", state: "Kerala" },
  { city: "Kozhikode", state: "Kerala" },
  { city: "Kollam", state: "Kerala" },
  { city: "Thrissur", state: "Kerala" },
  { city: "Alappuzha", state: "Kerala" },
  { city: "Palakkad", state: "Kerala" },

  // Assam
  { city: "Guwahati", state: "Assam" },
  { city: "Silchar", state: "Assam" },
  { city: "Dibrugarh", state: "Assam" },
  { city: "Jorhat", state: "Assam" },

  // Jammu & Kashmir
  { city: "Srinagar", state: "Jammu & Kashmir" },
  { city: "Jammu", state: "Jammu & Kashmir" },
  { city: "Anantnag", state: "Jammu & Kashmir" },

  // Chhattisgarh
  { city: "Raipur", state: "Chhattisgarh" },
  { city: "Bhilai", state: "Chhattisgarh" },
  { city: "Bilaspur", state: "Chhattisgarh" },
  { city: "Korba", state: "Chhattisgarh" },
  { city: "Rajnandgaon", state: "Chhattisgarh" },

  // Jharkhand
  { city: "Ranchi", state: "Jharkhand" },
  { city: "Jamshedpur", state: "Jharkhand" },
  { city: "Dhanbad", state: "Jharkhand" },
  { city: "Bokaro Steel City", state: "Jharkhand" },
  { city: "Deoghar", state: "Jharkhand" },
  { city: "Hazaribagh", state: "Jharkhand" },

  // Uttarakhand
  { city: "Dehradun", state: "Uttarakhand" },
  { city: "Haridwar", state: "Uttarakhand" },
  { city: "Haldwani", state: "Uttarakhand" },
  { city: "Roorkee", state: "Uttarakhand" },

  // Himachal Pradesh
  { city: "Shimla", state: "Himachal Pradesh" },
  { city: "Dharamshala", state: "Himachal Pradesh" },
  { city: "Solan", state: "Himachal Pradesh" },

  // Goa
  { city: "Panaji", state: "Goa" },
  { city: "Margao", state: "Goa" },
  { city: "Vasco da Gama", state: "Goa" },

  // Others/UTs
  { city: "Chandigarh", state: "Chandigarh" },
  { city: "Puducherry", state: "Puducherry" },
  { city: "Port Blair", state: "Andaman & Nicobar" },
  { city: "Itanagar", state: "Arunachal Pradesh" },
  { city: "Imphal", state: "Manipur" },
  { city: "Shillong", state: "Meghalaya" },
  { city: "Aizawl", state: "Mizoram" },
  { city: "Kohima", state: "Nagaland" },
  { city: "Gangtok", state: "Sikkim" },
  { city: "Agartala", state: "Tripura" },
  { city: "Leh", state: "Ladakh" },
  { city: "Kavaratti", state: "Lakshadweep" },
  { city: "Daman", state: "Dadra & Nagar Haveli and Daman & Diu" },
  { city: "Silvassa", state: "Dadra & Nagar Haveli and Daman & Diu" }
];
